#!/bin/bash
# Install a tightly-scoped passwordless sudo rule for Ivan (focus mode).
# Allows the current user to run only:
#   /usr/bin/tee /etc/hosts
#   /usr/bin/dscacheutil -flushcache
#   /usr/bin/killall -HUP mDNSResponder
# without a password prompt. Nothing else.
#
# Validated with `visudo -c` before installing. Revoke by deleting the file:
#   sudo rm /etc/sudoers.d/gbh-ivan

set -e

USER_NAME="$(id -un)"
SUDOERS_FILE="/etc/sudoers.d/gbh-ivan"
TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

cat > "$TMP_FILE" <<EOF
# GBH Ivan — focus mode passwordless sudo (scoped)
# Generated by scripts/install_ivan_sudoers.sh
$USER_NAME ALL=(root) NOPASSWD: /usr/bin/tee /etc/hosts
$USER_NAME ALL=(root) NOPASSWD: /usr/bin/dscacheutil -flushcache
$USER_NAME ALL=(root) NOPASSWD: /usr/bin/killall -HUP mDNSResponder
EOF
chmod 0440 "$TMP_FILE"

# Validate syntax before installing.
if ! /usr/sbin/visudo -cf "$TMP_FILE" >/dev/null; then
    echo "❌ sudoers syntax check failed. Aborting."
    exit 1
fi

echo "🔐 Ivan needs one sudo prompt to install /etc/sudoers.d/gbh-ivan."
echo "   After this, focus mode will never prompt for sudo again."
echo "   Revoke at any time:  sudo rm $SUDOERS_FILE"
echo ""

sudo install -o root -g wheel -m 0440 "$TMP_FILE" "$SUDOERS_FILE"
echo "   ✅ Installed $SUDOERS_FILE for user '$USER_NAME'"
